"""Add foreign keys to ContestRanking

Revision ID: 147f09d52f5a
Revises: 4bc70061164f
Create Date: 2025-04-12 16:30:24.287211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147f09d52f5a'
down_revision = '4bc70061164f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_ranking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contest_ranking')
    # ### end Alembic commands ###
